SELECT
	App.MarketAppId,
	App.MarketName,
	App.`Name`,
	App.EngName,
	App.Catalog,
	App.SubCatalog,
	App.Size,
	App.FreeSize,
	App.DownloadUrl,
	App.LogoUrl,
	App.Description,
	App.UpdateInfo,
	App.PublisherShortName,
	App.Version,
	App.Minsdkversion,
	App.VersionCode,
	App.OSVersion,
	App.Pkname,
	App.LastUpdateTime,
	App.LastFetchTime,
	App.DetailUrl,
	App.Price,
	App.Screens,
	App.Models,
	App.Keywords,
	App.StarRating,
	App.ViewCount,
	App.Downloads,
	App.DownloadRank,
	App.Supportpad,
	App.EnumStatus,
	App.StrImageUrls,
	App.AuditCatalog,
	App.Hidden,
	App.PageUrl,
	App.ShortDesc,
	App.IndexImgUrl,
	App.Notice,
	App.OfficeHomepage,
	App.`Language`,
	App.Audit,
	App.PathStatus,
	App.Permissions,
	App.SignatureSHA1,
	App.OfficialSigSHA1,
	App.ApkScanTime,
	App.Advertises,
	App.AdActionTypes,
	App.AdPopupTypes,
	App.Spite,
	App.AdRisk,
	App.RealDownload,
	App.DeltaDownload,
	App.LastDayDownload,
	App.LastDayDelta,
	App.LastWeekDownload,
	App.LastWeekDelta,
	App.VirusKind,
	App.VirusBehaviors,
	App.VirusName,
	App.Md5,
	App.AppId,
	App.ApkId,
	App.Logo1Url,
	App.`Status`,
	App.AutoCover,
	CASE  
        WHEN ((a.`Status` & 12288)= 4096)  then 0 
        WHEN ((a.`Status` & 12288)= 8192)  then 1
        WHEN ((a.`Status` & 12288)= 12288)  then 2 
        ELSE  0 
    END  AS StatusAudit 
FROM
App


    