package com.kingsoft.sjk.po;

// Generated 2012-7-25 16:50:31 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AndroidApp generated by hbm2java
 */
@Entity
@Table(name = "AndroidApp", catalog = "AppMgr")
public class AndroidApp implements java.io.Serializable {

    private static final long serialVersionUID = -2887782548166939807L;
    private Integer id;
    private String version;
    private String appId;
    private String name;
    private String originalName;
    private String otherNames;
    private String publisherShortName;
    private String publisherDetailName;
    private Double price;
    private Integer catalog;
    private Integer subCatalog;
    private Date updateDate;
    private Long size;
    private String language;
    private Integer ageLimit;
    private String osversion;
    private String resolution;
    private String platform;
    private String description;
    private String updateInfo;
    private String associateIds;
    private Integer rank;
    private String logo;
    private String qrcode;
    private String downLoadLink;
    private Date postDate;
    private Date editDate;
    private String poster;
    private Character state;
    private Character haveData;
    private String permit;
    private Date eupdateDate;
    private Character isGray;
    private Integer osversionGroupId;
    private Integer authType;
    private Integer sourceId;
    private String sourceUrl;
    private String pkname;
    private Integer versionCode;
    private Byte isReview;
    private Byte allowGuest;
    private Byte allowRepeat;
    private Integer softType;
    private Integer noStandardVersion;

    public AndroidApp() {
    }

    public AndroidApp(String appId, String name, String originalName, String otherNames, String publisherShortName,
            String publisherDetailName, Double price, Integer catalog, Integer subCatalog, Date updateDate, Long size,
            String language, Integer ageLimit, String osversion, String resolution, String platform,
            String description, String updateInfo, String associateIds, Integer rank, String logo, String qrcode,
            String downLoadLink, Date postDate, Date editDate, String poster, Character state, Character haveData,
            String permit, Date eupdateDate, Character isGray, Integer osversionGroupId, Integer authType,
            Integer sourceId, String sourceUrl, String pkname, Integer versionCode, Byte isReview, Byte allowGuest,
            Byte allowRepeat, Integer softType, Integer noStandardVersion) {
        this.appId = appId;
        this.name = name;
        this.originalName = originalName;
        this.otherNames = otherNames;
        this.publisherShortName = publisherShortName;
        this.publisherDetailName = publisherDetailName;
        this.price = price;
        this.catalog = catalog;
        this.subCatalog = subCatalog;
        this.updateDate = updateDate;
        this.size = size;
        this.language = language;
        this.ageLimit = ageLimit;
        this.osversion = osversion;
        this.resolution = resolution;
        this.platform = platform;
        this.description = description;
        this.updateInfo = updateInfo;
        this.associateIds = associateIds;
        this.rank = rank;
        this.logo = logo;
        this.qrcode = qrcode;
        this.downLoadLink = downLoadLink;
        this.postDate = postDate;
        this.editDate = editDate;
        this.poster = poster;
        this.state = state;
        this.haveData = haveData;
        this.permit = permit;
        this.eupdateDate = eupdateDate;
        this.isGray = isGray;
        this.osversionGroupId = osversionGroupId;
        this.authType = authType;
        this.sourceId = sourceId;
        this.sourceUrl = sourceUrl;
        this.pkname = pkname;
        this.versionCode = versionCode;
        this.isReview = isReview;
        this.allowGuest = allowGuest;
        this.allowRepeat = allowRepeat;
        this.softType = softType;
        this.noStandardVersion = noStandardVersion;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "Version", length = 20)
    public String getVersion() {
        return this.version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    @Column(name = "AppID", length = 100)
    public String getAppId() {
        return this.appId;
    }

    public void setAppId(String appId) {
        this.appId = appId;
    }

    @Column(name = "Name", length = 200)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "OriginalName", length = 200)
    public String getOriginalName() {
        return this.originalName;
    }

    public void setOriginalName(String originalName) {
        this.originalName = originalName;
    }

    @Column(name = "OtherNames", length = 200)
    public String getOtherNames() {
        return this.otherNames;
    }

    public void setOtherNames(String otherNames) {
        this.otherNames = otherNames;
    }

    @Column(name = "PublisherShortName", length = 200)
    public String getPublisherShortName() {
        return this.publisherShortName;
    }

    public void setPublisherShortName(String publisherShortName) {
        this.publisherShortName = publisherShortName;
    }

    @Column(name = "PublisherDetailName", length = 200)
    public String getPublisherDetailName() {
        return this.publisherDetailName;
    }

    public void setPublisherDetailName(String publisherDetailName) {
        this.publisherDetailName = publisherDetailName;
    }

    @Column(name = "Price", precision = 22, scale = 0)
    public Double getPrice() {
        return this.price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    @Column(name = "Catalog")
    public Integer getCatalog() {
        return this.catalog;
    }

    public void setCatalog(Integer catalog) {
        this.catalog = catalog;
    }

    @Column(name = "SubCatalog")
    public Integer getSubCatalog() {
        return this.subCatalog;
    }

    public void setSubCatalog(Integer subCatalog) {
        this.subCatalog = subCatalog;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UpdateDate", length = 19)
    public Date getUpdateDate() {
        return this.updateDate;
    }

    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    @Column(name = "Size")
    public Long getSize() {
        return this.size;
    }

    public void setSize(Long size) {
        this.size = size;
    }

    @Column(name = "Language", length = 50)
    public String getLanguage() {
        return this.language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    @Column(name = "AgeLimit")
    public Integer getAgeLimit() {
        return this.ageLimit;
    }

    public void setAgeLimit(Integer ageLimit) {
        this.ageLimit = ageLimit;
    }

    @Column(name = "OSVersion")
    public String getOsversion() {
        return this.osversion;
    }

    public void setOsversion(String osversion) {
        this.osversion = osversion;
    }

    @Column(name = "Resolution")
    public String getResolution() {
        return this.resolution;
    }

    public void setResolution(String resolution) {
        this.resolution = resolution;
    }

    @Column(name = "Platform")
    public String getPlatform() {
        return this.platform;
    }

    public void setPlatform(String platform) {
        this.platform = platform;
    }

    @Column(name = "Description")
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "UpdateInfo")
    public String getUpdateInfo() {
        return this.updateInfo;
    }

    public void setUpdateInfo(String updateInfo) {
        this.updateInfo = updateInfo;
    }

    @Column(name = "AssociateIDs", length = 100)
    public String getAssociateIds() {
        return this.associateIds;
    }

    public void setAssociateIds(String associateIds) {
        this.associateIds = associateIds;
    }

    @Column(name = "Rank")
    public Integer getRank() {
        return this.rank;
    }

    public void setRank(Integer rank) {
        this.rank = rank;
    }

    @Column(name = "Logo", length = 50)
    public String getLogo() {
        return this.logo;
    }

    public void setLogo(String logo) {
        this.logo = logo;
    }

    @Column(name = "QRCode", length = 50)
    public String getQrcode() {
        return this.qrcode;
    }

    public void setQrcode(String qrcode) {
        this.qrcode = qrcode;
    }

    @Column(name = "DownLoadLink", length = 50)
    public String getDownLoadLink() {
        return this.downLoadLink;
    }

    public void setDownLoadLink(String downLoadLink) {
        this.downLoadLink = downLoadLink;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "PostDate", length = 19)
    public Date getPostDate() {
        return this.postDate;
    }

    public void setPostDate(Date postDate) {
        this.postDate = postDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "EditDate", length = 19)
    public Date getEditDate() {
        return this.editDate;
    }

    public void setEditDate(Date editDate) {
        this.editDate = editDate;
    }

    @Column(name = "Poster", length = 25)
    public String getPoster() {
        return this.poster;
    }

    public void setPoster(String poster) {
        this.poster = poster;
    }

    @Column(name = "State", length = 1)
    public Character getState() {
        return this.state;
    }

    public void setState(Character state) {
        this.state = state;
    }

    @Column(name = "HaveData", length = 1)
    public Character getHaveData() {
        return this.haveData;
    }

    public void setHaveData(Character haveData) {
        this.haveData = haveData;
    }

    @Column(name = "Permit")
    public String getPermit() {
        return this.permit;
    }

    public void setPermit(String permit) {
        this.permit = permit;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "EUpdateDate", length = 19)
    public Date getEupdateDate() {
        return this.eupdateDate;
    }

    public void setEupdateDate(Date eupdateDate) {
        this.eupdateDate = eupdateDate;
    }

    @Column(name = "IsGray", length = 1)
    public Character getIsGray() {
        return this.isGray;
    }

    public void setIsGray(Character isGray) {
        this.isGray = isGray;
    }

    @Column(name = "OSVersionGroupID")
    public Integer getOsversionGroupId() {
        return this.osversionGroupId;
    }

    public void setOsversionGroupId(Integer osversionGroupId) {
        this.osversionGroupId = osversionGroupId;
    }

    @Column(name = "AuthType")
    public Integer getAuthType() {
        return this.authType;
    }

    public void setAuthType(Integer authType) {
        this.authType = authType;
    }

    @Column(name = "SourceID")
    public Integer getSourceId() {
        return this.sourceId;
    }

    public void setSourceId(Integer sourceId) {
        this.sourceId = sourceId;
    }

    @Column(name = "SourceUrl")
    public String getSourceUrl() {
        return this.sourceUrl;
    }

    public void setSourceUrl(String sourceUrl) {
        this.sourceUrl = sourceUrl;
    }

    @Column(name = "PKName")
    public String getPkname() {
        return this.pkname;
    }

    public void setPkname(String pkname) {
        this.pkname = pkname;
    }

    @Column(name = "VersionCode")
    public Integer getVersionCode() {
        return this.versionCode;
    }

    public void setVersionCode(Integer versionCode) {
        this.versionCode = versionCode;
    }

    @Column(name = "IsReview")
    public Byte getIsReview() {
        return this.isReview;
    }

    public void setIsReview(Byte isReview) {
        this.isReview = isReview;
    }

    @Column(name = "AllowGuest")
    public Byte getAllowGuest() {
        return this.allowGuest;
    }

    public void setAllowGuest(Byte allowGuest) {
        this.allowGuest = allowGuest;
    }

    @Column(name = "AllowRepeat")
    public Byte getAllowRepeat() {
        return this.allowRepeat;
    }

    public void setAllowRepeat(Byte allowRepeat) {
        this.allowRepeat = allowRepeat;
    }

    @Column(name = "SoftType")
    public Integer getSoftType() {
        return this.softType;
    }

    public void setSoftType(Integer softType) {
        this.softType = softType;
    }

    @Column(name = "NoStandardVersion")
    public Integer getNoStandardVersion() {
        return this.noStandardVersion;
    }

    public void setNoStandardVersion(Integer noStandardVersion) {
        this.noStandardVersion = noStandardVersion;
    }

}
