package com.ijinshan.sjk.po;

// Generated 2012-10-8 16:46:40 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Rollinfo generated by hbm2java
 */
@Entity
@Table(name = "Rollinfo", catalog = "AndroidMarket")
public class Rollinfo implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    protected int appId;
    protected boolean recommend;
    protected int rank;
    protected short catalog;

    public Rollinfo() {
    }

    public Rollinfo(int appId, boolean recommend, int rank, short catalog) {
        this.appId = appId;
        this.recommend = recommend;
        this.rank = rank;
        this.catalog = catalog;
    }

    @Id
    @Column(name = "AppId", unique = true, nullable = false)
    public int getAppId() {
        return this.appId;
    }

    public void setAppId(int appId) {
        this.appId = appId;
    }

    @Column(name = "Recommend", nullable = false)
    public boolean isRecommend() {
        return this.recommend;
    }

    public void setRecommend(boolean recommend) {
        this.recommend = recommend;
    }

    @Column(name = "Rank", nullable = false)
    public int getRank() {
        return this.rank;
    }

    public void setRank(int rank) {
        this.rank = rank;
    }

    @Column(name = "Catalog", nullable = false)
    public short getCatalog() {
        return this.catalog;
    }

    public void setCatalog(short catalog) {
        this.catalog = catalog;
    }

}
