package com.ijinshan.sjk.po;

// Generated 2013-1-8 15:05:30 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * BigGamePack generated by hbm2java
 */
@Entity
@Table(name = "BigGamePack", catalog = "AndroidMarket")
public class BigGamePack implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private Integer bigGamePackId;
    private int marketAppId;
    private byte cputype;
    private String url;
    private int size;
    private long freeSize;
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date marketUpdateTime;
    private String unsupportPhoneType;

    public BigGamePack() {
    }

    public BigGamePack(int marketAppId, byte cputype, String url, int size, long freeSize) {
        this.marketAppId = marketAppId;
        this.cputype = cputype;
        this.url = url;
        this.size = size;
        this.freeSize = freeSize;
    }

    private BigGamePack(Integer bigGamePackId, int marketAppId, byte cputype, String url, int size, long freeSize,
            Date marketUpdateTime, String unsupportPhoneType) {
        super();
        this.bigGamePackId = bigGamePackId;
        this.marketAppId = marketAppId;
        this.cputype = cputype;
        this.url = url;
        this.size = size;
        this.freeSize = freeSize;
        this.marketUpdateTime = marketUpdateTime;
        this.unsupportPhoneType = unsupportPhoneType;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "Id", unique = true, nullable = false)
    public Integer getBigGamePackId() {
        return bigGamePackId;
    }

    public void setBigGamePackId(Integer bigGamePackId) {
        this.bigGamePackId = bigGamePackId;
    }

    @Column(name = "MarketAppId", nullable = false)
    public int getMarketAppId() {
        return this.marketAppId;
    }

    public void setMarketAppId(int marketAppId) {
        this.marketAppId = marketAppId;
    }

    @Column(name = "Cputype", nullable = false)
    public byte getCputype() {
        return this.cputype;
    }

    public void setCputype(byte cputype) {
        this.cputype = cputype;
    }

    @Column(name = "Url", nullable = false, length = 200)
    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    @Column(name = "Size", nullable = false)
    public int getSize() {
        return this.size;
    }

    public void setSize(int size) {
        this.size = size;
    }

    @Column(name = "FreeSize", nullable = false)
    public long getFreeSize() {
        return this.freeSize;
    }

    public void setFreeSize(long freeSize) {
        this.freeSize = freeSize;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "MarketUpdateTime", length = 19)
    public Date getMarketUpdateTime() {
        return this.marketUpdateTime;
    }

    public void setMarketUpdateTime(Date marketUpdateTime) {
        this.marketUpdateTime = marketUpdateTime;
    }

    @Column(name = "UnsupportPhoneType")
    public String getUnsupportPhoneType() {
        return unsupportPhoneType;
    }

    public void setUnsupportPhoneType(String unsupportPhoneType) {
        this.unsupportPhoneType = unsupportPhoneType;
    }
}
