package com.ijinshan.sjk.po;

// Generated 2013-3-28 14:03:03 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * CatalogConvertor generated by hbm2java
 */
@Entity
@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
@Table(name = "CatalogConvertor", catalog = "AndroidMarket", uniqueConstraints = @UniqueConstraint(columnNames = {
        "Catalog", "MarketName", "SubCatalog" }))
public class CatalogConvertor implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private Integer id;
    private String marketName;
    private short catalog;
    private int subCatalog;
    private String subCatalogName;
    private short targetCatalog;
    private int targetSubCatalog;

    public CatalogConvertor() {
    }

    public CatalogConvertor(String marketName, short catalog, int subCatalog, String subCatalogName,
            short targetCatalog, int targetSubCatalog) {
        this.marketName = marketName;
        this.catalog = catalog;
        this.subCatalog = subCatalog;
        this.subCatalogName = subCatalogName;
        this.targetCatalog = targetCatalog;
        this.targetSubCatalog = targetSubCatalog;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "Id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "MarketName", nullable = false, length = 20)
    public String getMarketName() {
        return this.marketName;
    }

    public void setMarketName(String marketName) {
        this.marketName = marketName;
    }

    @Column(name = "Catalog", nullable = false)
    public short getCatalog() {
        return this.catalog;
    }

    public void setCatalog(short catalog) {
        this.catalog = catalog;
    }

    @Column(name = "SubCatalog", nullable = false)
    public int getSubCatalog() {
        return this.subCatalog;
    }

    public void setSubCatalog(int subCatalog) {
        this.subCatalog = subCatalog;
    }

    @Column(name = "SubCatalogName", nullable = false, length = 10)
    public String getSubCatalogName() {
        return this.subCatalogName;
    }

    public void setSubCatalogName(String subCatalogName) {
        this.subCatalogName = subCatalogName;
    }

    @Column(name = "TargetCatalog", nullable = false)
    public short getTargetCatalog() {
        return this.targetCatalog;
    }

    public void setTargetCatalog(short targetCatalog) {
        this.targetCatalog = targetCatalog;
    }

    @Column(name = "TargetSubCatalog", nullable = false)
    public int getTargetSubCatalog() {
        return this.targetSubCatalog;
    }

    public void setTargetSubCatalog(int targetSubCatalog) {
        this.targetSubCatalog = targetSubCatalog;
    }

}
