package com.ijinshan.sjk.po;

// Generated 2013-3-28 14:03:03 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * Market generated by hbm2java
 */
@Entity
@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
@Table(name = "Market", catalog = "AndroidMarket", uniqueConstraints = @UniqueConstraint(columnNames = "MarketName"))
public class Market implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private Integer id;
    private String marketName;
    private int rank;
    private String allowAccessKey;
    private String loginKey;
    private String security;
    private int pageSize;
    private String fullUrl;
    private Date fullLastTime;
    private int fullTotalPages;
    private int fullLastReqCurrentPage;
    private String incrementUrl;
    private Date incrementLastTime;
    private int incrementTotalPages;
    private int incrementLastReqCurrentPage;
    private String status;

    public Market() {
    }

    public Market(String marketName, int rank, String allowAccessKey, String loginKey, String security, int pageSize,
            int fullTotalPages, int fullLastReqCurrentPage, int incrementTotalPages, int incrementLastReqCurrentPage,
            String status) {
        this.marketName = marketName;
        this.rank = rank;
        this.allowAccessKey = allowAccessKey;
        this.loginKey = loginKey;
        this.security = security;
        this.pageSize = pageSize;
        this.fullTotalPages = fullTotalPages;
        this.fullLastReqCurrentPage = fullLastReqCurrentPage;
        this.incrementTotalPages = incrementTotalPages;
        this.incrementLastReqCurrentPage = incrementLastReqCurrentPage;
        this.status = status;
    }

    public Market(String marketName, int rank, String allowAccessKey, String loginKey, String security, int pageSize,
            String fullUrl, Date fullLastTime, int fullTotalPages, int fullLastReqCurrentPage, String incrementUrl,
            Date incrementLastTime, int incrementTotalPages, int incrementLastReqCurrentPage, String status) {
        this.marketName = marketName;
        this.rank = rank;
        this.allowAccessKey = allowAccessKey;
        this.loginKey = loginKey;
        this.security = security;
        this.pageSize = pageSize;
        this.fullUrl = fullUrl;
        this.fullLastTime = fullLastTime;
        this.fullTotalPages = fullTotalPages;
        this.fullLastReqCurrentPage = fullLastReqCurrentPage;
        this.incrementUrl = incrementUrl;
        this.incrementLastTime = incrementLastTime;
        this.incrementTotalPages = incrementTotalPages;
        this.incrementLastReqCurrentPage = incrementLastReqCurrentPage;
        this.status = status;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "Id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "MarketName", unique = true, nullable = false, length = 20)
    public String getMarketName() {
        return this.marketName;
    }

    public void setMarketName(String marketName) {
        this.marketName = marketName;
    }

    @Column(name = "Rank", nullable = false)
    public int getRank() {
        return this.rank;
    }

    public void setRank(int rank) {
        this.rank = rank;
    }

    @Column(name = "AllowAccessKey", nullable = false, length = 32)
    public String getAllowAccessKey() {
        return this.allowAccessKey;
    }

    public void setAllowAccessKey(String allowAccessKey) {
        this.allowAccessKey = allowAccessKey;
    }

    @Column(name = "LoginKey", nullable = false, length = 36)
    public String getLoginKey() {
        return this.loginKey;
    }

    public void setLoginKey(String loginKey) {
        this.loginKey = loginKey;
    }

    @Column(name = "Security", nullable = false, length = 45)
    public String getSecurity() {
        return this.security;
    }

    public void setSecurity(String security) {
        this.security = security;
    }

    @Column(name = "PageSize", nullable = false)
    public int getPageSize() {
        return this.pageSize;
    }

    public void setPageSize(int pageSize) {
        this.pageSize = pageSize;
    }

    @Column(name = "FullUrl", length = 450)
    public String getFullUrl() {
        return this.fullUrl;
    }

    public void setFullUrl(String fullUrl) {
        this.fullUrl = fullUrl;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "FullLastTime", length = 19)
    public Date getFullLastTime() {
        return this.fullLastTime;
    }

    public void setFullLastTime(Date fullLastTime) {
        this.fullLastTime = fullLastTime;
    }

    @Column(name = "FullTotalPages", nullable = false)
    public int getFullTotalPages() {
        return this.fullTotalPages;
    }

    public void setFullTotalPages(int fullTotalPages) {
        this.fullTotalPages = fullTotalPages;
    }

    @Column(name = "FullLastReqCurrentPage", nullable = false)
    public int getFullLastReqCurrentPage() {
        return this.fullLastReqCurrentPage;
    }

    public void setFullLastReqCurrentPage(int fullLastReqCurrentPage) {
        this.fullLastReqCurrentPage = fullLastReqCurrentPage;
    }

    @Column(name = "IncrementUrl", length = 450)
    public String getIncrementUrl() {
        return this.incrementUrl;
    }

    public void setIncrementUrl(String incrementUrl) {
        this.incrementUrl = incrementUrl;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "IncrementLastTime", length = 19)
    public Date getIncrementLastTime() {
        return this.incrementLastTime;
    }

    public void setIncrementLastTime(Date incrementLastTime) {
        this.incrementLastTime = incrementLastTime;
    }

    @Column(name = "IncrementTotalPages", nullable = false)
    public int getIncrementTotalPages() {
        return this.incrementTotalPages;
    }

    public void setIncrementTotalPages(int incrementTotalPages) {
        this.incrementTotalPages = incrementTotalPages;
    }

    @Column(name = "IncrementLastReqCurrentPage", nullable = false)
    public int getIncrementLastReqCurrentPage() {
        return this.incrementLastReqCurrentPage;
    }

    public void setIncrementLastReqCurrentPage(int incrementLastReqCurrentPage) {
        this.incrementLastReqCurrentPage = incrementLastReqCurrentPage;
    }

    @Column(name = "Status", nullable = false, length = 5)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

}
