package com.ijinshan.sjk.po;

// Generated 2013-1-31 9:48:56 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * MoAppAndTag generated by hbm2java
 */
@Entity
@Table(name = "Mo_AppAndTag", catalog = "AndroidMarket")
public class MoAppAndTag implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private Integer id;
    private int appId;
    private int tagId;
    private int rank;
    private String tagName;
    private short tagType;
    private String shortDesc;
    private transient MoTag moTag;
    private App app;

    public MoAppAndTag() {
    }

    public MoAppAndTag(int appId, int tagId, int rank, String tagName, short tagType, String shortDesc) {
        this.appId = appId;
        this.tagId = tagId;
        this.rank = rank;
        this.tagName = tagName;
        this.tagType = tagType;
        this.shortDesc = shortDesc;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "Id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "AppId", nullable = false)
    public int getAppId() {
        return this.appId;
    }

    public void setAppId(int appId) {
        this.appId = appId;
    }

    @Column(name = "TagId", nullable = false)
    public int getTagId() {
        return this.tagId;
    }

    public void setTagId(int tagId) {
        this.tagId = tagId;
    }

    @Column(name = "Rank", nullable = false)
    public int getRank() {
        return this.rank;
    }

    public void setRank(int rank) {
        this.rank = rank;
    }

    @Column(name = "TagName", nullable = false, length = 20)
    public String getTagName() {
        return this.tagName;
    }

    public void setTagName(String tagName) {
        this.tagName = tagName;
    }

    @Column(name = "TagType", nullable = false)
    public short getTagType() {
        return this.tagType;
    }

    public void setTagType(short tagType) {
        this.tagType = tagType;
    }

    @Column(name = "ShortDesc", nullable = false, length = 45)
    public String getShortDesc() {
        return this.shortDesc;
    }

    public void setShortDesc(String shortDesc) {
        this.shortDesc = shortDesc;
    }

    @Transient
    public App getApp() {
        return app;
    }

    public void setApp(App app) {
        this.app = app;
    }

    @ManyToOne(fetch = FetchType.LAZY, targetEntity = MoTag.class)
    @JoinColumn(name = "TagId", nullable = false, insertable = false, updatable = false)
    // FK
    public MoTag getMoTag() {
        return moTag;
    }

    public void setMoTag(MoTag moTag) {
        this.moTag = moTag;
    }

}
