package com.ijinshan.sjk.po;

// Generated 2013-3-28 14:03:03 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * MoFeatured generated by hbm2java
 */
@Entity
@Table(name = "Mo_Featured", catalog = "AndroidMarket", uniqueConstraints = @UniqueConstraint(columnNames = { "Type",
        "AppOrTagId" }))
public class MoFeatured implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private Integer id;
    private int appOrTagId;
    private short type;
    private short picType;
    private String name;
    private int rank;
    private String pics;
    private String shortDesc;
    private boolean deleted;
    private boolean hidden;
    private Date opTime;
    private String bigPics;

    public MoFeatured() {
    }

    public MoFeatured(int appOrTagId, short type, short picType, String name, int rank, String pics, String shortDesc,
            boolean deleted, boolean hidden, Date opTime, String bigPics) {
        this.appOrTagId = appOrTagId;
        this.type = type;
        this.picType = picType;
        this.name = name;
        this.rank = rank;
        this.pics = pics;
        this.shortDesc = shortDesc;
        this.deleted = deleted;
        this.hidden = hidden;
        this.opTime = opTime;
        this.bigPics = bigPics;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "Id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "AppOrTagId", nullable = false)
    public int getAppOrTagId() {
        return this.appOrTagId;
    }

    public void setAppOrTagId(int appOrTagId) {
        this.appOrTagId = appOrTagId;
    }

    @Column(name = "Type", nullable = false)
    public short getType() {
        return this.type;
    }

    public void setType(short type) {
        this.type = type;
    }

    @Column(name = "PicType", nullable = false)
    public short getPicType() {
        return this.picType;
    }

    public void setPicType(short picType) {
        this.picType = picType;
    }

    @Column(name = "Name", nullable = false, length = 50)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "Rank", nullable = false)
    public int getRank() {
        return this.rank;
    }

    public void setRank(int rank) {
        this.rank = rank;
    }

    @Column(name = "Pics", nullable = false, length = 65535)
    public String getPics() {
        return this.pics;
    }

    public void setPics(String pics) {
        this.pics = pics;
    }

    @Column(name = "ShortDesc", nullable = false, length = 200)
    public String getShortDesc() {
        return this.shortDesc;
    }

    public void setShortDesc(String shortDesc) {
        this.shortDesc = shortDesc;
    }

    @Column(name = "Deleted", nullable = false)
    public boolean isDeleted() {
        return this.deleted;
    }

    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }

    @Column(name = "Hidden", nullable = false)
    public boolean isHidden() {
        return this.hidden;
    }

    public void setHidden(boolean hidden) {
        this.hidden = hidden;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "OpTime", nullable = false, length = 19)
    public Date getOpTime() {
        return this.opTime;
    }

    public void setOpTime(Date opTime) {
        this.opTime = opTime;
    }

    @Column(name = "BigPics")
    public String getBigPics() {
        return bigPics;
    }

    public void setBigPics(String bigPics) {
        this.bigPics = bigPics;
    }

}
