package com.ijinshan.sjk.po;

// Generated 2013-3-28 14:03:03 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * MoFeatured generated by hbm2java
 */
@Entity
@Table(name = "Mo_MixFeatured", catalog = "AndroidMarket", uniqueConstraints = @UniqueConstraint(columnNames = {
        "Type", "AppOrTagId" }))
public class MoMixFeatured implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private Integer id;
    private int appOrTagId;
    private short type;
    private short picType;
    private String name;
    private int rank;
    private String shortDesc;
    private boolean hidden;
    private Date opTime;
    private String bigPics;
    private String mediumPics;
    private String smallPics;

    public MoMixFeatured() {
    }

    @Override
    public String toString() {
        return "MoMixFeatured [id=" + id + ", appOrTagId=" + appOrTagId + ", type=" + type + ", picType=" + picType
                + ", name=" + name + ", rank=" + rank + ", shortDesc=" + shortDesc + ", hidden=" + hidden + ", opTime="
                + opTime + ", bigPics=" + bigPics + ", mediumPics=" + mediumPics + ", smallPics=" + smallPics + "]";
    }

    public MoMixFeatured(int appOrTagId, short type, short picType, String name, int rank, String shortDesc,
            boolean hidden, Date opTime, String bigPics) {
        this.appOrTagId = appOrTagId;
        this.type = type;
        this.picType = picType;
        this.name = name;
        this.rank = rank;
        this.shortDesc = shortDesc;
        this.hidden = hidden;
        this.opTime = opTime;
        this.bigPics = bigPics;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "Id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "AppOrTagId", nullable = false)
    public int getAppOrTagId() {
        return this.appOrTagId;
    }

    public void setAppOrTagId(int appOrTagId) {
        this.appOrTagId = appOrTagId;
    }

    @Column(name = "Type", nullable = false)
    public short getType() {
        return this.type;
    }

    public void setType(short type) {
        this.type = type;
    }

    @Column(name = "PicType", nullable = false)
    public short getPicType() {
        return this.picType;
    }

    public void setPicType(short picType) {
        this.picType = picType;
    }

    @Column(name = "Name", nullable = false, length = 50)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "Rank", nullable = false)
    public int getRank() {
        return this.rank;
    }

    public void setRank(int rank) {
        this.rank = rank;
    }

    @Column(name = "ShortDesc", nullable = false, length = 200)
    public String getShortDesc() {
        return this.shortDesc;
    }

    public void setShortDesc(String shortDesc) {
        this.shortDesc = shortDesc;
    }

    @Column(name = "Hidden", nullable = false)
    public boolean isHidden() {
        return this.hidden;
    }

    public void setHidden(boolean hidden) {
        this.hidden = hidden;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "OpTime", nullable = false, length = 19)
    public Date getOpTime() {
        return this.opTime;
    }

    public void setOpTime(Date opTime) {
        this.opTime = opTime;
    }

    @Column(name = "BigPics", nullable = false, length = 255)
    public String getBigPics() {
        return bigPics;
    }

    public void setBigPics(String bigPics) {
        this.bigPics = bigPics;
    }

    @Column(name = "MediumPics", nullable = false, length = 255)
    public String getMediumPics() {
        return mediumPics;
    }

    public void setMediumPics(String mediumPics) {
        this.mediumPics = mediumPics;
    }

    @Column(name = "SmallPics", nullable = false, length = 255)
    public String getSmallPics() {
        return smallPics;
    }

    public void setSmallPics(String smallPics) {
        this.smallPics = smallPics;
    }

}
