package com.ijinshan.sjk.po;

// Generated 2012-10-8 16:46:40 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AppAndTag generated by hbm2java
 */
@Entity
@Table(name = "VI_MoTagApps", catalog = "AndroidMarket")
public class MoViewTagApps implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private Integer id;
    private int appId;
    private String marketName;
    private String appName;
    private int tagId;
    private int catalog;
    private int appCatalog;
    private String logoUrl;
    private Integer rank;
    private String tagName;
    private String shortDesc;
    private short tagType;

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "Id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "MarketName", nullable = false)
    public String getMarketName() {
        return marketName;
    }

    public void setMarketName(String marketName) {
        this.marketName = marketName;
    }

    @Column(name = "AppName", nullable = false)
    public String getAppName() {
        return appName;
    }

    public void setAppName(String appName) {
        this.appName = appName;
    }

    public static long getSerialversionuid() {
        return serialVersionUID;
    }

    @Column(name = "AppId", nullable = false)
    public int getAppId() {
        return this.appId;
    }

    public void setAppId(int appId) {
        this.appId = appId;
    }

    @Column(name = "ShortDesc", nullable = false)
    public String getShortDesc() {
        return shortDesc;
    }

    public void setShortDesc(String shortDesc) {
        this.shortDesc = shortDesc;
    }

    @Column(name = "TagId", nullable = false)
    public int getTagId() {
        return this.tagId;
    }

    public void setTagId(int tagId) {
        this.tagId = tagId;
    }

    @Column(name = "Rank")
    public Integer getRank() {
        return this.rank;
    }

    public void setRank(Integer rank) {
        this.rank = rank;
    }

    @Column(name = "TagName", nullable = false, length = 20)
    public String getTagName() {
        return this.tagName;
    }

    public void setTagName(String tagName) {
        this.tagName = tagName;
    }

    @Column(name = "TagType", nullable = false)
    public short getTagType() {
        return this.tagType;
    }

    public void setTagType(short tagType) {
        this.tagType = tagType;
    }

    @Column(name = "Catalog", nullable = false)
    public int getCatalog() {
        return catalog;
    }

    public void setCatalog(int catalog) {
        this.catalog = catalog;
    }

    @Column(name = "AppCatalog", nullable = false)
    public int getAppCatalog() {
        return appCatalog;
    }

    public void setAppCatalog(int appCatalog) {
        this.appCatalog = appCatalog;
    }

    @Column(name = "LogoUrl", nullable = false)
    public String getLogoUrl() {
        return logoUrl;
    }

    public void setLogoUrl(String logoUrl) {
        this.logoUrl = logoUrl;
    }

}
