package com.ijinshan.sjk.po;

// Generated 2013-4-10 14:54:01 by Hibernate Tools 3.4.0.CR1
import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * TopApp generated by hbm2java
 */
@Entity
@Table(name = "TopApp", catalog = "AndroidMarket", uniqueConstraints = @UniqueConstraint(columnNames = { "Id", "AppId" }))
public class TopApp implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private int id;
    private int appId;
    private String name;
    private String pkname;
    private String newName;
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date lastUpdateTime;
    private byte state;

    public TopApp() {
        super();
    }

    public TopApp(int id, int appId, String name, String pkname, Date lastUpdateTime) {
        this.id = id;
        this.appId = appId;
        this.name = name;
        this.pkname = pkname;
        this.lastUpdateTime = lastUpdateTime;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "Id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "AppId", nullable = false)
    public int getAppId() {
        return this.appId;
    }

    public void setAppId(int appId) {
        this.appId = appId;
    }

    @Column(name = "Name", nullable = false, length = 80)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "Pkname", nullable = false, length = 200)
    public String getPkname() {
        return this.pkname;
    }

    public void setPkname(String pkname) {
        this.pkname = pkname;
    }

    @Column(name = "NewName", length = 80)
    public String getNewName() {
        return this.newName;
    }

    public void setNewName(String newName) {
        this.newName = newName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LastUpdateTime", nullable = false, length = 19)
    public Date getLastUpdateTime() {
        return this.lastUpdateTime;
    }

    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }
    @Column(name = "State", length = 1)
    public byte getState() {
        return state;
    }

    public void setState(byte state) {
        this.state = state;
    }
}
