package com.ijinshan.sjk.po;

// Generated 2012-4-24 15:20:59 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "User", catalog = "AndroidMarket", uniqueConstraints = @UniqueConstraint(columnNames = "Name"))
public class User implements java.io.Serializable {

    private static final long serialVersionUID = 4697861071808642168L;
    private Integer id;
    private String name;
    private String password;
    private String email;
    private String actualName;
    private String mobile;
    private String workTel;
    private Short userType;

    public User() {
    }

    public User(String name, String password, String actualName) {
        this.name = name;
        this.password = password;
        this.actualName = actualName;
    }

    public User(String name, String password, String email, String actualName, String mobile, String workTel,
            Short userType) {
        this.name = name;
        this.password = password;
        this.email = email;
        this.actualName = actualName;
        this.mobile = mobile;
        this.workTel = workTel;
        this.userType = userType;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "Id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "Name", unique = true, nullable = false, length = 30)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "Password", nullable = false, length = 32)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Column(name = "Email")
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "ActualName", nullable = false, length = 25)
    public String getActualName() {
        return this.actualName;
    }

    public void setActualName(String actualName) {
        this.actualName = actualName;
    }

    @Column(name = "Mobile", length = 20)
    public String getMobile() {
        return this.mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    @Column(name = "WorkTel", length = 10)
    public String getWorkTel() {
        return this.workTel;
    }

    public void setWorkTel(String workTel) {
        this.workTel = workTel;
    }

    @Column(name = "UserType")
    public Short getUserType() {
        return this.userType;
    }

    public void setUserType(Short userType) {
        this.userType = userType;
    }

}
