package com.kingsoft.sjk.po;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

/**
 * AppAndTag generated by hbm2java
 */
@Entity
// @Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
// @Table(name = "AppAndTag", catalog = "AndroidMarket")
public class AppTags implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private int id;
    private int appId;
    private int tagId;
    private Integer rank;
    private String tagName;
    private short tagType;

    public AppTags() {
    }

    public AppTags(int appId, int tagId, Integer rank, String tagName, short tagType) {
        super();
        this.appId = appId;
        this.tagId = tagId;
        this.rank = rank;
        this.tagName = tagName;
        this.tagType = tagType;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "Id", unique = true, nullable = false)
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "AppId", nullable = false)
    public int getAppId() {
        return appId;
    }

    public void setAppId(int appId) {
        this.appId = appId;
    }

    @Column(name = "TagId", nullable = false)
    public int getTagId() {
        return tagId;
    }

    public void setTagId(int tagId) {
        this.tagId = tagId;
    }

    @Column(name = "Rank", nullable = false)
    public Integer getRank() {
        return rank;
    }

    public void setRank(Integer rank) {
        this.rank = rank;
    }

    @Column(name = "TagName", nullable = false)
    public String getTagName() {
        return tagName;
    }

    public void setTagName(String tagName) {
        this.tagName = tagName;
    }

    @Column(name = "TagType", nullable = false)
    public short getTagType() {
        return tagType;
    }

    public void setTagType(short tagType) {
        this.tagType = tagType;
    }

    @Override
    public String toString() {
        return "AppTags [id=" + id + ", appId=" + appId + ", tagId=" + tagId + ", rank=" + rank + ", tagName="
                + tagName + ", tagType=" + tagType + "]";
    }

}
