package com.kingsoft.sjk.po;

// Generated 2012-9-3 14:58:38 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Catalog generated by hbm2java
 */
@Entity
// @Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
@Table(name = "Catalog", catalog = "AndroidMarket")
public class Catalog implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private Integer id;
    private int pid;
    private String name;
    private Integer rank;
    private String keywords;
    private String description;

    public Catalog() {
    }

    public Catalog(int pid, String name, String keywords) {
        this.pid = pid;
        this.name = name;
        this.keywords = keywords;
    }

    public Catalog(int pid, String name, Integer rank, String keywords, String description) {
        this.pid = pid;
        this.name = name;
        this.rank = rank;
        this.keywords = keywords;
        this.description = description;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "Id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "PId", nullable = false)
    public int getPid() {
        return this.pid;
    }

    public void setPid(int pid) {
        this.pid = pid;
    }

    @Column(name = "Name", nullable = false, length = 10)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "Rank")
    public Integer getRank() {
        return this.rank;
    }

    public void setRank(Integer rank) {
        this.rank = rank;
    }

    @Column(name = "Keywords", nullable = false, length = 200)
    public String getKeywords() {
        return this.keywords;
    }

    public void setKeywords(String keywords) {
        this.keywords = keywords;
    }

    @Column(name = "Description")
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

}
